Server:
  RunMode: debug
  HttpPort: 8050
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100

Database:
  DBType: mysql
  Username: root
  Password: 123456
  Port: 3306
  DBName: fiber
  Charset: utf8mb4
  Loc: Local
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 30
  TablePrefix: fiber_

Logger:
  FilePath: ./output/log/log.txt
  MaxSize: 1
  MaxBackups: 30
  MaxAge: 30
  Compress: false
  LocalTime: true